user:
  #username 学号或者工号
  username: '240105010619'
  #tellphone 电话号码
  tellphone: '13732918977'
  #address 地址，定位信息
  address: 中国江西省南昌市新建区
  #email 接受通知消息的邮箱
  email: 3074324245@qq.com
  #school 学校全称
  school: 南昌理工学院
  #lon 当前位置经度
  lon: '115.8631542856856'
  #lat 当前位置纬度
  lat: '28.787776764202917'
  #abnormalReason 反馈信息，不需要可不填
  abnormalReason: 在家
  #photo 签到照片，不需要可不填
  photo:
#今日校园相关配置
cpdaily:
  #附加信息组默认选项配置，没有可留空
  defaults:
    #附加信息组默认选项配置，按顺序，可留空
    - default:
        title: 晚检体温(必填)
        value: 小于37.3度
    - default:
        title: 是否有发热、咳嗽、乏力、呼吸困难等疑似症状(必填)
        value: 否
